name: provider_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  audioplayers: ^1.0.1
  connectivity_plus: ^2.2.0
  cupertino_icons: ^1.0.2
  either_dart: ^0.1.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.7.0
  flutter_sound: ^9.2.13
  freezed_annotation: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.4.0
  painter: ^2.0.0
  permission_handler: ^10.0.0
  provider: ^6.0.2
  rxdart: ^0.27.4
  share_plus: ^4.0.10
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.12
  image_picker: ^0.8.5+3
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  google_sign_in: ^4.5.9
  device_preview: ^1.0.0
  flutter_staggered_grid_view: ^0.6.2
  path_provider: ^2.0.11
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  
 
  
  
  
  
dev_dependencies:
  flutter_driver:
    sdk: flutter
  # package for lint rules.
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  # freezed model generator.
 
  # Package used for the integration testing.
  integration_test:
    sdk: flutter
  # Package for json serialization.
  json_serializable: ^6.1.5
  dependencies:
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.10.0

  flutter_icons:
  android: true
  ios: true

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
      - image/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
